# Generated by Django 4.0.1 on 2022-01-19 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_product_category_alter_product_tags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
